##############################################server配置#################################################
server:
  servlet:
    context-path: /phoenix-ui
    session:
      timeout: 30m
  undertow:
    accesslog:
      #Undertow日志存放目录
      dir: liblog4phoenix/logs/phoenix-ui
      #是否启动日志
      enabled: true
      #日志格式
      pattern: common
      #日志文件名前缀
      #prefix: access_log
      #日志文件名后缀
      #suffix: log
  #开启优雅停机
  shutdown: graceful


###############################################日志配置####################################################
logging:
  config: classpath:logback-spring.xml
  #监控相关的日志级别设置成info
  level:
    org.springframework.retry.support.RetryTemplate: trace
    com.gitee.pifeng.monitoring: info
    oshi: error


###############################################spring配置#################################################
spring:
  session:
    store-type: jdbc
  mvc:
    async:
      #接口访问超时时间
      request-timeout: 5000
  jackson:
    #设置时区
    time-zone: GMT+8
  #main:
  #支持名称相同的bean的覆盖
  #allow-bean-definition-overriding: true
  application:
    name: phoenix-ui
  profiles:
    active:
      - dev
  devtools:
    livereload:
      port: 35732
  lifecycle:
    #设置缓冲期，最大等待时间
    timeout-per-shutdown-phase: 30s


  ############################################thymeleaf配置###############################################
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8


  ###############################################数据源配置##################################################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化来连接大小
      initial-size: 5
      #连接池中最小的空闲连接数
      min-idle: 5
      #连接池中使用的最大连接数量
      max-active: 100
      #获取连接的最大等待时间，单位毫秒
      max-wait: 60000
      #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      #建议配置为true，不影响性能，并且保证安全性。 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #标记是否删除泄露的连接
      #remove-abandoned: true
      #泄露的连接可以被删除的超时时间（秒），该值应设置为应用程序查询可能执行的最长时间，1800秒，也就是30分钟
      remove-abandoned-timeout: 1800
      #删除泄露的连接时是否输出错误日志
      log-abandoned: true
      #打开PSCache，并且指定每个连接上PSCache的大小，PSCache对支持游标的数据库性能提升巨大，比如说oracle
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 20
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #web监控
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        profile-enable: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: true
        #允许所有访问
        allow:
      #监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        wall:
          enabled: true
        config:
          enabled: true
        encoding:
          enabled: true
        stat:
          enabled: true
        commons-log:
          enabled: true
        slf4j:
          enabled: true
      #Spring监控配置
      aop-patterns: com.gitee.pifeng.monitoring.ui.business.web.*


#############################################mybatis-plus配置#############################################
mybatis-plus:
  #启动时是否检查MyBatis XML文件的存在，默认不检查
  check-config-location: false
  #扫描mapper文件的位置
  mapper-locations:
    - classpath:com/gitee/pifeng/monitoring/ui/business/**/mapper/*Mapper.xml
  configuration:
    #是否开启缓存
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: null
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    #打印sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #数据库厂商标识
    database-id: mysql
  #如果插件版本是3.0-gamma这个选项必须配置,否则会nullPoint
  global-config:
    db-config:
      #数据库类型(已弃用3.1.1，这个属性没什么用)
      #db-type: mysql
      #主键类型  AUTO："数据库ID自增"，INPUT："用户输入ID"，ID_WORKER："全局唯一ID (数字类型唯一ID)"，UUID:"全局唯一ID UUID"
      id-type: auto
      #字段策略 IGNORED："忽略判断"，NOT_NULL："非 NULL 判断"，NOT_EMPTY："非空判断"(已弃用3.1.2)
      #field-strategy: not-empty
      #数据库大写下划线转换
      capital-mode: false
      #表名，是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true


############################################springboot端点配置#############################################
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
  server:
    #处于安全考虑，只允许在本地进行关闭操作
    address: 127.0.0.1


##############################################knife4j配置#################################################
knife4j:
  enable: true
  setting:
    language: zh-CN
  basic:
    enable: true
    username: admin
    password: admin