# 使用 YAML 锚点实现日志配置复用
x-logconfig: &default-logconfig
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  phoenix-mysql:
    container_name: phoenix-mysql
    image: crpi-4iaxdbbs1euymfiu.cn-shanghai.personal.cr.aliyuncs.com/pifeng_phoenix/mysql:1.2.6.RELEASE-CR4
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - /data/phoenix/mysql/data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    logging: *default-logconfig

  phoenix-server:
    container_name: phoenix-server
    image: crpi-4iaxdbbs1euymfiu.cn-shanghai.personal.cr.aliyuncs.com/pifeng_phoenix/phoenix-server:1.2.6.RELEASE-CR4
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/phoenix/phoenix-server/liblog4phoenix:/app/liblog4phoenix
      - /data/phoenix/phoenix-server/config:/app/config
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    depends_on:
      phoenix-mysql:
        condition: service_started
    logging: *default-logconfig

  phoenix-ui:
    container_name: phoenix-ui
    image: crpi-4iaxdbbs1euymfiu.cn-shanghai.personal.cr.aliyuncs.com/pifeng_phoenix/phoenix-ui:1.2.6.RELEASE-CR4
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/phoenix/phoenix-ui/liblog4phoenix:/app/liblog4phoenix
      - /data/phoenix/phoenix-ui/config:/app/config
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    depends_on:
      phoenix-mysql:
        condition: service_started
      phoenix-server:
        condition: service_started
    logging: *default-logconfig